const PDFDocument = require('pdfkit');

/**
 * Generate a professional PDF payment receipt
 * @param {object} payment - Populated payment document
 * @param {object} gym - Gym document
 * @returns {Promise<Buffer>} PDF buffer
 */
const generatePdfReceipt = ({ payment, gym }) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers = [];

    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // ─── Header ─────────────────────────────────────────────────────────────
    doc.fontSize(24).font('Helvetica-Bold').text('PAYMENT RECEIPT', { align: 'center' });
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#6366f1').lineWidth(2).stroke();
    doc.moveDown();

    // ─── Gym Info ───────────────────────────────────────────────────────────
    doc.fontSize(16).font('Helvetica-Bold').text(gym.name, { align: 'center' });
    if (gym.address?.city) {
      doc.fontSize(10).font('Helvetica').fillColor('#6b7280').text(
        [gym.address.street, gym.address.city, gym.address.state, gym.address.pincode].filter(Boolean).join(', '),
        { align: 'center' },
      );
    }
    if (gym.phone) {
      doc.text(`Phone: ${gym.phone}`, { align: 'center' });
    }
    doc.fillColor('#000000');
    doc.moveDown();

    // ─── Receipt Details ────────────────────────────────────────────────────
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').lineWidth(1).stroke();
    doc.moveDown(0.5);

    const addRow = (label, value, color = '#000000') => {
      const y = doc.y;
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#6b7280').text(label, 50, y, { width: 200 });
      doc.fontSize(11).font('Helvetica').fillColor(color).text(String(value), 260, y, { width: 285 });
      doc.moveDown(0.6);
    };

    addRow('Receipt Number:', payment.receiptNumber);
    addRow('Date:', new Date(payment.paidAt || payment.createdAt).toLocaleDateString('en-IN', {
      day: 'numeric', month: 'long', year: 'numeric',
    }));

    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').lineWidth(1).stroke();
    doc.moveDown(0.5);

    // Member Info
    doc.fontSize(12).font('Helvetica-Bold').text('MEMBER DETAILS');
    doc.moveDown(0.4);

    const member = payment.member;
    addRow('Member Name:', member?.name || '—');
    addRow('Member ID:', member?.memberId || '—');
    addRow('Phone:', member?.phone || '—');

    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').lineWidth(1).stroke();
    doc.moveDown(0.5);

    // Payment Info
    doc.fontSize(12).font('Helvetica-Bold').text('PAYMENT DETAILS');
    doc.moveDown(0.4);

    const plan = payment.membershipPlan;
    if (plan) addRow('Plan:', plan.name);
    addRow('Payment Method:', payment.method?.toUpperCase());
    addRow('Status:', payment.status?.toUpperCase(), payment.status === 'paid' ? '#16a34a' : '#dc2626');
    if (payment.periodStart) {
      addRow('Period Start:', new Date(payment.periodStart).toLocaleDateString('en-IN'));
    }
    if (payment.periodEnd) {
      addRow('Period End:', new Date(payment.periodEnd).toLocaleDateString('en-IN'));
    }
    if (payment.notes) addRow('Notes:', payment.notes);

    // ─── Amount Box ─────────────────────────────────────────────────────────
    doc.moveDown();
    const boxY = doc.y;
    doc.rect(50, boxY, 495, 60).fillColor('#f0fdf4').fill();
    doc.rect(50, boxY, 495, 60).strokeColor('#16a34a').lineWidth(1.5).stroke();
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#16a34a').text('AMOUNT PAID', 70, boxY + 15);
    doc.fontSize(22).font('Helvetica-Bold').fillColor('#16a34a').text(`₹${payment.amount.toLocaleString('en-IN')}`, 350, boxY + 12, {
      width: 175, align: 'right',
    });

    // ─── Footer ─────────────────────────────────────────────────────────────
    doc.fillColor('#000000');
    doc.moveDown(3);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').lineWidth(1).stroke();
    doc.moveDown(0.5);
    doc.fontSize(9).font('Helvetica').fillColor('#9ca3af').text(
      'This is a computer-generated receipt and does not require a signature.',
      { align: 'center' },
    );
    doc.text(`Generated by GymOS • ${new Date().toLocaleDateString('en-IN')}`, { align: 'center' });

    doc.end();
  });
};

module.exports = { generatePdfReceipt };
