/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectGymRouteImport } from './routes/select-gym'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as CreateGymRouteImport } from './routes/create-gym'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrainersRouteImport } from './routes/_app.trainers'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPlansRouteImport } from './routes/_app.plans'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppMealsRouteImport } from './routes/_app.meals'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppExercisesRouteImport } from './routes/_app.exercises'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppMembersIndexRouteImport } from './routes/_app.members.index'
import { Route as AppMembersAddRouteImport } from './routes/_app.members.add'
import { Route as AppMembersIdRouteImport } from './routes/_app.members.$id'

const SelectGymRoute = SelectGymRouteImport.update({
  id: '/select-gym',
  path: '/select-gym',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateGymRoute = CreateGymRouteImport.update({
  id: '/create-gym',
  path: '/create-gym',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrainersRoute = AppTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppMealsRoute = AppMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersIndexRoute = AppMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersAddRoute = AppMembersAddRouteImport.update({
  id: '/members/add',
  path: '/members/add',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersIdRoute = AppMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-gym': typeof CreateGymRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-gym': typeof SelectGymRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/exercises': typeof AppExercisesRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/meals': typeof AppMealsRoute
  '/payments': typeof AppPaymentsRoute
  '/plans': typeof AppPlansRoute
  '/settings': typeof AppSettingsRoute
  '/trainers': typeof AppTrainersRoute
  '/members/$id': typeof AppMembersIdRoute
  '/members/add': typeof AppMembersAddRoute
  '/members/': typeof AppMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-gym': typeof CreateGymRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-gym': typeof SelectGymRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/exercises': typeof AppExercisesRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/meals': typeof AppMealsRoute
  '/payments': typeof AppPaymentsRoute
  '/plans': typeof AppPlansRoute
  '/settings': typeof AppSettingsRoute
  '/trainers': typeof AppTrainersRoute
  '/members/$id': typeof AppMembersIdRoute
  '/members/add': typeof AppMembersAddRoute
  '/members': typeof AppMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/create-gym': typeof CreateGymRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-gym': typeof SelectGymRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/exercises': typeof AppExercisesRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/meals': typeof AppMealsRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/plans': typeof AppPlansRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/trainers': typeof AppTrainersRoute
  '/_app/members/$id': typeof AppMembersIdRoute
  '/_app/members/add': typeof AppMembersAddRoute
  '/_app/members/': typeof AppMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-gym'
    | '/register'
    | '/reset-password'
    | '/select-gym'
    | '/attendance'
    | '/dashboard'
    | '/exercises'
    | '/leaderboard'
    | '/meals'
    | '/payments'
    | '/plans'
    | '/settings'
    | '/trainers'
    | '/members/$id'
    | '/members/add'
    | '/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-gym'
    | '/register'
    | '/reset-password'
    | '/select-gym'
    | '/attendance'
    | '/dashboard'
    | '/exercises'
    | '/leaderboard'
    | '/meals'
    | '/payments'
    | '/plans'
    | '/settings'
    | '/trainers'
    | '/members/$id'
    | '/members/add'
    | '/members'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/create-gym'
    | '/register'
    | '/reset-password'
    | '/select-gym'
    | '/_app/attendance'
    | '/_app/dashboard'
    | '/_app/exercises'
    | '/_app/leaderboard'
    | '/_app/meals'
    | '/_app/payments'
    | '/_app/plans'
    | '/_app/settings'
    | '/_app/trainers'
    | '/_app/members/$id'
    | '/_app/members/add'
    | '/_app/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CreateGymRoute: typeof CreateGymRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectGymRoute: typeof SelectGymRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-gym': {
      id: '/select-gym'
      path: '/select-gym'
      fullPath: '/select-gym'
      preLoaderRoute: typeof SelectGymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-gym': {
      id: '/create-gym'
      path: '/create-gym'
      fullPath: '/create-gym'
      preLoaderRoute: typeof CreateGymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trainers': {
      id: '/_app/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof AppTrainersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meals': {
      id: '/_app/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AppMealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises': {
      id: '/_app/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/': {
      id: '/_app/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AppMembersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/add': {
      id: '/_app/members/add'
      path: '/members/add'
      fullPath: '/members/add'
      preLoaderRoute: typeof AppMembersAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/$id': {
      id: '/_app/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof AppMembersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExercisesRoute: typeof AppExercisesRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMealsRoute: typeof AppMealsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPlansRoute: typeof AppPlansRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrainersRoute: typeof AppTrainersRoute
  AppMembersIdRoute: typeof AppMembersIdRoute
  AppMembersAddRoute: typeof AppMembersAddRoute
  AppMembersIndexRoute: typeof AppMembersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExercisesRoute: AppExercisesRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMealsRoute: AppMealsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPlansRoute: AppPlansRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrainersRoute: AppTrainersRoute,
  AppMembersIdRoute: AppMembersIdRoute,
  AppMembersAddRoute: AppMembersAddRoute,
  AppMembersIndexRoute: AppMembersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CreateGymRoute: CreateGymRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectGymRoute: SelectGymRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
